**4.1**

Problem - 1: Array Creation:

1

In [ ]:
import numpy as np

array = np.empty((2, 2))
print(array)


[[0. 0.]
 [0. 0.]]


2

In [ ]:
import numpy as np

array = np.ones((4, 2))
print(array)


[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


3

In [ ]:
import numpy as np

array = np.full((3, 3), 7)
print(array)


[[7 7 7]
 [7 7 7]
 [7 7 7]]


4

In [ ]:
import numpy as np

#Given array
array = np.array([[10, 20, 30], [40, 50, 60]])


zero_array = np.zeros_like(array)
print(zero_array)


[[0 0 0]
 [0 0 0]]


5

In [ ]:
import numpy as np

#Given array
array = np.array([[10, 20, 30], [40, 50, 60]])

ones_array = np.ones_like(array)
print(ones_array)


[[1 1 1]
 [1 1 1]]


6

In [ ]:
import numpy as np

#The existing list
new_list = [1, 2, 3, 4]

array = np.array(new_list)
print(array)


[1 2 3 4]


**4.1.1 Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:**

1

In [ ]:
import numpy as np

array = np.arange(10, 50)
print(array)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2

In [ ]:
import numpy as np

# Creating an array with values ranging from 0 to 8
array = np.arange(9)

# Reshaping it into a 3x3 matrix
matrix = array.reshape(3, 3)
print(matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


3

In [ ]:
import numpy as np

# Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4

In [ ]:
import numpy as np

# Creating a random array of size 30
array = np.random.random(30)

# Calculating the mean of the array
mean = array.mean()

# print("Random Array:", array)
print("Mean of the array:", mean)


Mean of the array: 0.4585107463518365


5

In [ ]:
import numpy as np

# Creating a random 10x10 array
array = np.random.random((10, 10))

# Minimum and maximum values
min_value = array.min()
max_value = array.max()

print("Random 10x10 Array:")
print(array)
print("\nMinimum value:", min_value)
print("Maximum value:", max_value)


Random 10x10 Array:
[[6.28523806e-01 4.37233461e-01 4.81836334e-01 3.69945504e-01
  7.02378018e-02 8.45501990e-01 7.37532166e-01 7.31170906e-01
  8.81542590e-01 6.32434109e-01]
 [3.03824594e-01 4.02260199e-01 7.77312069e-01 4.11574521e-01
  2.02748059e-01 9.97293934e-02 1.35102560e-01 7.62520736e-01
  5.84292765e-01 9.52177937e-02]
 [2.99027941e-01 1.85389923e-01 7.96440085e-01 7.19862399e-01
  2.28016240e-01 2.34971862e-01 9.99402587e-01 7.19116119e-01
  1.58806014e-01 5.85509551e-01]
 [4.21689687e-02 4.69627550e-01 8.66143120e-01 4.72313648e-01
  4.98745420e-01 3.37335088e-01 6.80625016e-01 9.73088567e-01
  5.54656154e-01 3.52006270e-01]
 [7.15548194e-01 1.72245055e-01 7.39733517e-01 2.74500114e-01
  5.37264727e-01 9.65339718e-01 7.39627040e-01 5.71311630e-01
  4.16379092e-01 2.88018675e-02]
 [2.64094148e-01 3.85442495e-06 3.93269548e-02 5.18848510e-01
  7.89764748e-01 2.17022871e-01 1.70658461e-01 6.54851969e-01
  2.68901288e-01 9.46209249e-01]
 [2.99368840e-01 7.55164513e-01 7.4056

6

In [ ]:
import numpy as np

# Creating a zero array of size 10
array = np.zeros(10)

# Replacing the 5th element (index 4) with 1
array[4] = 1

print(array)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7


In [ ]:
array = [1, 2, 0, 0, 4, 0]

# Reversing
reversed = array[::-1]

print(reversed)


[0, 4, 0, 0, 2, 1]


8

In [ ]:
import numpy as np

# Define the size of the array (e.g., 5x5)
size = 4

# Create a 2D array of zeros
array = np.zeros((size, size), dtype=int)

# Set the border elements to 1
array[0, :] = 1  # Top border
array[-1, :] = 1  # Bottom border
array[:, 0] = 1  # Left border
array[:, -1] = 1  # Right border

print(array)


[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


9

In [ ]:
import numpy as np

# Creating an 8x8 matrix of zeros
matrix = np.zeros((8, 8), dtype=int)

# Filling the matrix with a checkerboard pattern
matrix[::2, ::2] = 1  # Set 1's on even rows and columns
matrix[1::2, 1::2] = 1  # Set 1's on odd rows and columns

print(matrix)


[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


Problem - 3: Array Operations:
For the following arrays:

x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);

v = np.array([9,10]) and w = np.array([11,12]);

Complete all the task using numpy:

1

In [ ]:
import numpy as np

# Array
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

v = np.array([9,10])
w = np.array([11,12]);

# Add the two arrays
sum = x + y
sum_1 = v+w


print("Sum of x and y:")
print(sum)
print()
print("Sum of v and w:")
print(sum_1)


Sum of x and y:
[[ 6  8]
 [10 13]]

Sum of v and w:
[20 22]


2

In [ ]:
import numpy as np

# Array
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

v = np.array([9,10])
w = np.array([11,12]);

# Subtracting the two arrays
diff = y - x
diff_1 = w - v

print("Difference of x and y:")
print(diff)
print()
print("Difference of w and v:")
print(diff_1)


Difference of x and y:
[[4 4]
 [4 3]]

Difference of w and v:
[2 2]


3

In [ ]:
import numpy as np

# Array
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

v = np.array([9,10])
w = np.array([11,12]);

X=x*2;
Y=y*3
V=v*4
W=w*5;

print("Array x multiplied by 2:")
print(X)
print("Array y multiplied by 3:")
print(Y)
print("Array v multiplied by 4:")
print(V)
print("Array w multiplied by 5:")
print(W)

Array x multiplied by 2:
[[ 2  4]
 [ 6 10]]
Array y multiplied by 3:
[[15 18]
 [21 24]]
Array v multiplied by 4:
[36 40]
Array w multiplied by 5:
[55 60]


4

In [ ]:
import numpy as np

# Array
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

v = np.array([9,10])
w = np.array([11,12]);

X=x**2;
Y=y**2;
V=v**2;
W=w**2;

print("Array x squared:")
print(X)
print("Array y squared:")
print(Y)
print("Array V squared:")
print(V)
print("Array W squared:")
print(W)

Array x squared:
[[ 1  4]
 [ 9 25]]
Array y squared:
[[25 36]
 [49 64]]
Array V squared:
[ 81 100]
Array W squared:
[121 144]


5

In [ ]:
import numpy as np

# Define the arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# Compute the dot product of v and w
v_dot_w = np.dot(v, w)

# Compute the dot product of x and v
x_dot_v = np.dot(x, v)

# Compute the dot product of x and y
x_dot_y = np.dot(x, y)

# Print the results
print("Dot product of v and w:", v_dot_w)
print("Dot product of x and v:", x_dot_v)
print("Dot product of x and y:", x_dot_y)


Dot product of v and w: 219
Dot product of x and v: [29 77]
Dot product of x and y: [[19 22]
 [50 58]]


6

In [ ]:
import numpy as np

# Arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# Stack x and y along rows using np.vstack()
x_and_y_row = np.vstack((x, y))

# Stack v and w along columns using np.vstack() after reshaping
v_and_w_column = np.vstack((v, w)).T  # Transpose to make it column-wise

# Print the results
print("Stacked x and y along rows using np.vstack():")
print(x_and_y_row)

print("\nStacked v and w along columns using np.vstack():")
print(v_and_w_column)


Stacked x and y along rows using np.vstack():
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

Stacked v and w along columns using np.vstack():
[[ 9 11]
 [10 12]]


7

In [ ]:
import numpy as np

# Arrays
x = np.array([[1, 2], [3, 5]])  # 2D array (2x2)
v = np.array([9, 10])           # 1D array (1x2)

# Concatenating
try:
    result = np.concatenate((x, v), axis=0)  # Concatenate along axis 0 (rows)
    print("Concatenated array:")
    print(result)
except ValueError as e:
    print("Error:")
    print(e)


Error:
all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


**Problem - 4: Matrix Operations:**

1

In [ ]:
import numpy as np

# Define matrices
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A * A^-1 = I
A_inv = np.linalg.inv(A)
I = np.dot(A, A_inv)
print("1. A * A^-1 = I:")
print(np.round(I))  # Rounded to avoid small numerical inaccuracies
print("Therefore, A*A^-1 = I proved.")

# 2. Prove AB != BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\n2. AB and BA:")
print("AB:\n", AB)
print("BA:\n", BA)
print("Therefore, AB !=BA proved.")

# 3. Prove (AB)^T = B^T * A^T
AB_T = np.transpose(AB)
BT_AT = np.dot(B.T, A.T)
print("\n3. (AB)^T and B^T * A^T:")
print("(AB)^T:\n", AB_T)
print("B^T * A^T:\n", BT_AT)
print("Therefore, (AB)^T = B^T * A^T proved.")


1. A * A^-1 = I:
[[1. 0.]
 [0. 1.]]
Therefore, A*A^-1 = I proved.

2. AB and BA:
AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
Therefore, AB !=BA proved.

3. (AB)^T and B^T * A^T:
(AB)^T:
 [[23 51]
 [13 29]]
B^T * A^T:
 [[23 51]
 [13 29]]
Therefore, (AB)^T = B^T * A^T proved.


2

In [ ]:
import numpy as np

# Coefficient matrix A
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3,  1, -1]])

# Constant matrix B
B = np.array([-1, -3, 9])

# Solve for X using the inverse method
A_inv = np.linalg.inv(A)  # Compute the inverse of A
X = np.dot(A_inv, B)      # Multiply A^-1 with B

# Print the solution
print("Solution (x, y, z):")
print(X)


Solution (x, y, z):
[ 2.  1. -2.]


**4.2 Experiment: How Fast is Numpy?**

1. Element-wise Addition:

In [1]:
# Import necessary libraries
import time
import numpy as np

# Element-wise addition using Python lists
# Create two Python lists of size 1,000,000
list1 = [i for i in range(1_000_000)]
list2 = [i for i in range(1_000_000)]

# Measure time for element-wise addition
start_time_list = time.time()
list_result = [list1[i] + list2[i] for i in range(len(list1))]
time_taken_list = time.time() - start_time_list

# Element-wise addition using NumPy arrays
# Create two NumPy arrays of size 1,000,000
array1 = np.arange(1_000_000)
array2 = np.arange(1_000_000)

# Measure time for element-wise addition
start_time_array = time.time()
array_result = array1 + array2
time_taken_array = time.time() - start_time_array

# Print results
print(f"Time taken using Python lists: {time_taken_list:.6f} seconds")
print(f"Time taken using NumPy arrays: {time_taken_array:.6f} seconds")


Time taken using Python lists: 0.193609 seconds
Time taken using NumPy arrays: 0.006929 seconds


**2. Element-wise Multiplication**

In [ ]:
# Import necessary libraries
import time
import numpy as np

# Create Python lists of size 1,000,000
list1 = [i for i in range(1_000_000)]
list2 = [i for i in range(1_000_000)]

# Measure time for element-wise multiplication using Python lists
start_time_list_mult = time.time()
list_result_mult = [list1[i] * list2[i] for i in range(len(list1))]
time_taken_list_mult = time.time() - start_time_list_mult

# Create NumPy arrays of size 1,000,000
array1 = np.arange(1_000_000)
array2 = np.arange(1_000_000)

# Measure time for element-wise multiplication using NumPy arrays
start_time_array_mult = time.time()
array_result_mult = array1 * array2
time_taken_array_mult = time.time() - start_time_array_mult

# Print results
print(f"Time taken for element-wise multiplication using Python lists: {time_taken_list_mult:.6f} seconds")
print(f"Time taken for element-wise multiplication using NumPy arrays: {time_taken_array_mult:.6f} seconds")


**3.Dot Product**

In [ ]:
# Import necessary libraries
import time
import numpy as np

# Create Python lists of size 1,000,000
list1 = [i for i in range(1_000_000)]
list2 = [i for i in range(1_000_000)]

# Measure time for dot product using Python lists
start_time_list_dot = time.time()
dot_product_list = sum(list1[i] * list2[i] for i in range(len(list1)))
time_taken_list_dot = time.time() - start_time_list_dot

# Create NumPy arrays of size 1,000,000
array1 = np.arange(1_000_000)
array2 = np.arange(1_000_000)

# Measure time for dot product using NumPy arrays
start_time_array_dot = time.time()
dot_product_array = np.dot(array1, array2)
time_taken_array_dot = time.time() - start_time_array_dot

# Print results
print(f"Time taken for dot product using Python lists: {time_taken_list_dot:.6f} seconds")
print(f"Time taken for dot product using NumPy arrays: {time_taken_array_dot:.6f} seconds")


**4. Matrix Multiplication**

In [2]:
# Import necessary libraries
import time
import numpy as np

# Create two 1000x1000 matrices using Python lists
matrix1_list = [[i + j for j in range(1000)] for i in range(1000)]
matrix2_list = [[i + j for j in range(1000)] for i in range(1000)]

# Measure time for matrix multiplication using Python lists
start_time_list_mult = time.time()
result_list = [[sum(matrix1_list[i][k] * matrix2_list[k][j] for k in range(1000))
                for j in range(1000)] for i in range(1000)]
time_taken_list_mult = time.time() - start_time_list_mult

# Create two 1000x1000 matrices using NumPy arrays
matrix1_array = np.random.rand(1000, 1000)
matrix2_array = np.random.rand(1000, 1000)

# Measure time for matrix multiplication using NumPy arrays
start_time_array_mult = time.time()
result_array = np.dot(matrix1_array, matrix2_array)
time_taken_array_mult = time.time() - start_time_array_mult

# Print results
print(f"Time taken for matrix multiplication using Python lists: {time_taken_list_mult:.6f} seconds")
print(f"Time taken for matrix multiplication using NumPy arrays: {time_taken_array_mult:.6f} seconds")


Time taken for matrix multiplication using Python lists: 259.032693 seconds
Time taken for matrix multiplication using NumPy arrays: 0.077256 seconds
